// ---------------------------------------------------------------------------
// SITE DATA — the business facts that don't change with language: contact
// details, links, image paths, and the ids the per-language dictionaries in
// data/locales/*.ts key their copy on. Every user-visible sentence lives there;
// the default language and the list of locales live in lib/i18n.ts.
// ---------------------------------------------------------------------------

export const business = {
  name: "Dredent Dental Clinic",
  phone: "+389 70 376 959",
  phoneHref: "tel:+38970376959",
  email: "dredentclinic@gmail.com",
  mapQuery: "Dredent+Dental+Clinic+Strasho+Pindjur+121+Tetovo",
  // Exact pin coordinates, copied from the clinic's Google Maps listing.
  geo: { lat: 42.013353, lng: 20.971293 },
  // Confirmed schedule. Day labels come from the dictionary (`hours`); `time: null`
  // renders as "closed". Keep components/json-ld.tsx openingHoursSpecification in sync.
  hours: [
    { id: "weekdays", time: "10:00 – 18:00" },
    { id: "saturday", time: "10:00 – 15:00" },
    { id: "sunday", time: null },
  ],
  social: {
    instagram: "https://www.instagram.com/dredentclinicandlab/",
    instagramHandle: "@dredentclinicandlab",
    facebook: "https://www.facebook.com/dredentclinic/",
  },
  bookingHref: "#contact",
} as const;

// Keyless Google Maps URLs — no API key to manage, and nothing loads from Google
// until the visitor clicks. `view` is the clinic's official share link (Google
// Maps → Share → "Send a link"); `directions` uses the Maps URLs API, so Google
// asks the visitor for their start point and the site never touches their location.
export const mapLinks = {
  view: "https://maps.app.goo.gl/eHsW9Q9bY4BZab189",
  directions: `https://www.google.com/maps/dir/?api=1&destination=${business.mapQuery}`,
} as const;

// The interactive map in the contact section is served entirely from this site
// (components/local-map.tsx): vector tiles for this area live in
// public/map/tetovo.pmtiles, cut from a Protomaps/OpenStreetMap build by
// scripts/build-map-tiles.mjs — keep these bounds in sync with that script.
export const mapArea = {
  bounds: [20.93, 41.98, 21.02, 42.05] as [number, number, number, number],
  minZoom: 12,
  maxZoom: 18,
  initialZoom: 15.5,
} as const;

// Curator.io feed for the Instagram section (mosaic template:
// https://curator.io/templates/mosaic). While feedId is empty the section keeps
// rendering its built-in placeholder mosaic; set the real values in .env.local
// (see .env.example) once the feed is created and published in Curator.
// Footer credit link. Leave `href` empty to render the credit as plain text.
export const credits = { href: "" } as const;

export const curatorFeed = {
  feedId: process.env.NEXT_PUBLIC_CURATOR_FEED_ID ?? "",
  containerId: process.env.NEXT_PUBLIC_CURATOR_CONTAINER_ID ?? "curator-feed-default-feed-layout",
} as const;

// Section anchors (rendered as /<locale>/#hash so they also work from the legal pages). Labels: dictionary `nav`.
export const nav = [
  { id: "about", hash: "#about" },
  { id: "services", hash: "#services" },
  { id: "transformations", hash: "#transformations" },
  { id: "stories", hash: "#stories" },
  { id: "faq", hash: "#faq" },
  { id: "contact", hash: "#contact" },
] as const;
export type NavId = (typeof nav)[number]["id"];

// Services — deliberately not numbered 01/02/03: there's no real sequence to them,
// a patient picks whichever one applies to them. Titles/descriptions: dictionary `services.items`.
export type ServiceIcon = "scan" | "gem" | "sparkles" | "layers" | "anchor" | "stethoscope";

export const services = [
  { id: "smile-design", icon: "scan" },
  { id: "veneers", icon: "gem" },
  { id: "whitening", icon: "sparkles" },
  { id: "aligners", icon: "layers" },
  { id: "implants", icon: "anchor" },
  { id: "general", icon: "stethoscope" },
] as const satisfies readonly { id: string; icon: ServiceIcon }[];
export type ServiceId = (typeof services)[number]["id"];

// Before / after pairs for the signature "Smile Reveal" compare slider. The files
// under public/results/ are aligned re-crops generated by scripts/align-results.mjs
// from the untouched originals in assets-src/results-original/.
//
// ⚠️ REAL PATIENT PHOTOS. Before launch: (1) confirm each patient's written
// consent to publish, (2) correct the title/procedure lines in the dictionaries
// (`gallery.cases`) — they are written from what the photos show, not from the
// clinic's records.
export const comparePairs = [
  { id: "case-01", beforeSrc: "/results/case-01-before.jpg", afterSrc: "/results/case-01-after.jpg" },
  { id: "case-02", beforeSrc: "/results/case-02-before.jpg", afterSrc: "/results/case-02-after.jpg" },
  { id: "case-03", beforeSrc: "/results/case-03-before.jpg", afterSrc: "/results/case-03-after.jpg" },
  { id: "case-04", beforeSrc: "/results/case-04-before.jpg", afterSrc: "/results/case-04-after.jpg" },
  { id: "case-05", beforeSrc: "/results/case-05-before.jpg", afterSrc: "/results/case-05-after.jpg" },
  { id: "case-06", beforeSrc: "/results/case-06-before.webp", afterSrc: "/results/case-06-after.webp" },
  { id: "case-07", beforeSrc: "/results/case-07-before.webp", afterSrc: "/results/case-07-after.webp" },
  { id: "case-08", beforeSrc: "/results/case-08-before.webp", afterSrc: "/results/case-08-after.webp" },
] as const;
export type CaseId = (typeof comparePairs)[number]["id"];

// Placeholder tiles for the Instagram-style mosaic. Swap `seed` values for real photo
// assets, and see components/instagram-mosaic.tsx for how to wire this to a live feed.
// Captions: dictionary `instagram.captions`.
export const instagramPosts = [
  { id: "ig-1", seed: "cusp-ig-1", likes: 214, big: true },
  { id: "ig-2", seed: "cusp-ig-2", likes: 98 },
  { id: "ig-3", seed: "cusp-ig-3", likes: 143 },
  { id: "ig-4", seed: "cusp-ig-4", likes: 176 },
  { id: "ig-5", seed: "cusp-ig-5", likes: 231, big: true },
  { id: "ig-6", seed: "cusp-ig-6", likes: 87 },
  { id: "ig-7", seed: "cusp-ig-7", likes: 165 },
  { id: "ig-8", seed: "cusp-ig-8", likes: 72 },
] as const satisfies readonly { id: string; seed: string; likes: number; big?: boolean }[];
export type PostId = (typeof instagramPosts)[number]["id"];

export const seo = {
  // TODO: replace with the real domain before launch — canonical URLs, hreflang
  // alternates, sitemap.xml, robots.txt, and Open Graph tags are all generated
  // from this value. Titles, descriptions and keywords: dictionary `seo`.
  siteUrl: "https://www.dredent.example",
} as const;
